[package]
name = "magnus"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4.11.0"
clap = { version = "4.5.50", features = ["derive", "env", "color", "std"] }
eyre = "0.6.12"
futures = "0.3.31"
futures-util = "0.3.31"
metrics = "0.24.2"
metrics-exporter-prometheus = "0.17.2"
secrecy = "0.10.3"
solana-cpi = "3.0.0"
solana-instruction = "3.0.0"
solana-sdk = "3.0.0"
solana-client = "3.0.8"
spl-associated-token-account = "8.0.0"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "time"] }
yellowstone-grpc-proto = "10.1.1"
yellowstone-grpc-client = "10.1.1"
anyhow = "1.0.100"
serde_json = "1.0.145"
reqwest = {version = "0.12.24"}
serde = { version = "1.0.228", features = ["derive"] }
tonic = { version = "0.14.2", features = ["tls-native-roots", "tls-ring"] }
spl-token = "9.0.0"
ahash = "0.8.12"
rust_decimal = { version = "1.39.0", features = ["macros"] }
num_cpus = "1.17.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["actix-web"] }
utoipa-rapidoc = { version = "6.0.0", features = ["actix-web"] }
utoipa-redoc = { version = "6.0.0", features = ["actix-web"] }
utoipa = { version = "5.4.0", features = ["actix_extras"] }

[dev-dependencies]
criterion = "0.7.0"


# temporary
[[bin]]
name = "solfi_swap"
path = "scripts/solfi_swap.rs"

[[bin]]
name = "raydium-clmm_swap"
path = "scripts/raydium_clmm_swap.rs"

[[bin]]
name = "raydium-cpmm_swap"
path = "scripts/raydium_cpamm_swap.rs"
