[package]
name = "magnus"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

# temporary
[[bin]]
name = "solfi_swap"
path = "scripts/solfi_swap.rs"

[[bin]]
name = "raydium-clmm_swap"
path = "scripts/raydium_clmm_swap.rs"

[[bin]]
name = "raydium-cpmm_swap"
path = "scripts/raydium_cpamm_swap.rs"

[dependencies]
actix-web = "4.11.0"
ahash = "0.8.12"
#anchor-client = { version = "0.31.0" }
anchor-lang = { version = "0.31.0" }
anchor-spl = { version = "0.31.0" }
#anchor-client = { version = "0.32.1" }
#anchor-lang = { version = "0.32.1" }
#anchor-spl = { version = "0.32.1" }
anyhow = "1.0.100"
async-trait = "0.1.89"
clap = { version = "4.5.50", features = ["derive", "env", "color", "std"] }
eyre = "0.6.12"
futures = "0.3.31"
futures-util = "0.3.31"
jupiter-amm-interface = "0.6.0"
metrics = "0.24.2"
metrics-exporter-prometheus = "0.17.2"
num_cpus = "1.17.0"

reqwest = { version = "0.12.24" }
rust_decimal = { version = "1.39.0", features = ["macros"] }
secrecy = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
solana-client = "3.0.8"
solana-cpi = "3.0.0"
solana-instruction = "3.0.0"
solana-sdk = "3.0.0"
solana-commitment-config = "3.1.0"
spl-associated-token-account = "8.0.0"
spl-token = "8.0.0"
#spl-token-swap = "3.0.0"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
tonic = { version = "0.14.2", features = ["tls-native-roots", "tls-ring"] }
tonic-health = "0.14.2"
tracing = "0.1.41"
tracing-actix-web = "0.7.19"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "time"] }
utoipa = { version = "5.4.0", features = ["actix_extras"] }
utoipa-rapidoc = { version = "6.0.0", features = ["actix-web"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["actix-web"] }
yellowstone-grpc-client = "10.1.1"
yellowstone-grpc-proto = "10.1.1"
arrayref = "0.3.9"
enum_dispatch = "0.3.13"
num-derive = "0.4"
num-traits = "0.2"
solana-program = "2.0.3"
spl-token-2022 = "10.0.0"
spl-math = "0.3.0"

raydium-cp-swap = { git = "https://github.com/raydium-io/raydium-cp-swap", package = "raydium-cp-swap", features = ["no-entrypoint", "client"] }
raydium-clmm = { git = "https://github.com/raydium-io/raydium-clmm", package = "raydium-amm-v3", features = ["no-entrypoint", "client"] }

[dev-dependencies]
criterion = "0.7.0"
proptest = "1.9.0"
