format_strings = true
reorder_impl_items = true
use_try_shorthand = true
remove_nested_parens = true
unstable_features = true
format_code_in_doc_comments = true
use_field_init_shorthand = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
max_width = 180
doc_comment_code_block_width = 100
comment_width = 100
single_line_if_else_max_width = 90
use_small_heuristics = "Max"
