cargo-features = ["edition2024"]

[package]
name = "magnus-shared"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
anchor-lang = { workspace = true }
magnus-router-client = { path = "../router-client" }
serde = { version = "1.0.228", features = ["derive"] }
